#!/bin/bash
#PBS -l walltime=1:00:00
#PBS -N L1stats-t1w
#PBS -q normal
#PBS -l nodes=1:ppn=28


# load modules and go to workdir
# module load fsl/6.0.2  # we shouldn't use the default version of fsl because it is old and has a bug
# instead, install fsl to your work directory and then ensure your ~/.bash_profile is set up with the correct paths. example below:
# # FSL Setup
# FSLDIR=~/work/tools/fsl_6.0.7
# . ${FSLDIR}/etc/fslconf/fsl.sh
# PATH=${FSLDIR}/bin:${PATH}
# export FSLDIR PATH


cd $PBS_O_WORKDIR
umask 0000

# ensure paths are correct
shareddir=/gpfs/scratch/tug87422/smithlab-shared
projectdir=$shareddir/night-owls
scriptdir=$projectdir/code
bidsdir=$projectdir/bids
logdir=$projectdir/logs
mkdir -p $logdir

rm -f $logdir/cmd_L1stats-t1w_${PBS_JOBID}.txt
touch $logdir/cmd_L1stats-t1w_${PBS_JOBID}.txt

rm -f L1stats-t1w.o*
rm -f L1stats-t1w.e*




DATA=${projectdir}/derivatives/fmriprep/sub-101/ses-03/func/sub-101_ses-03_task-mid_run-2_part-mag_space-T1w_desc-preproc_bold_5mm_match-run1grid.nii.gz
scriptname=${scriptdir}/L1stats-mid-t1w-test.sh
echo "bash ${scriptname} 101 03 2" >> $logdir/cmd_L1stats-t1w_${PBS_JOBID}.txt


torque-launch -p "$logdir/chk_L1stats-t1w_${PBS_JOBID}.txt" "$logdir/cmd_L1stats-t1w_${PBS_JOBID}.txt"
