#!/bin/bash
#PBS -l walltime=4:00:00
#PBS -N L1statsFIR
#PBS -q normal
#PBS -l nodes=1:ppn=28


cd $PBS_O_WORKDIR
umask 0000

# ensure paths are correct
shareddir=/gpfs/scratch/tug87422/smithlab-shared
projectdir=$shareddir/night-owls
scriptdir=$projectdir/code
bidsdir=$projectdir/bids
logdir=$projectdir/logs
mkdir -p $logdir

rm -f $logdir/cmd_L1stats_${sub}_${PBS_JOBID}.txt
touch $logdir/cmd_L1stats_${sub}_${PBS_JOBID}.txt

scriptname=${scriptdir}/L1stats-loop_FIR.sh

for sub in ${subjects[@]}; do
	for ses in {01..12}; do
		for run in 1 2; do
			echo "bash ${scriptname} ${sub} ${ses} ${run}" >> $logdir/cmd_L1stats_${sub}_${PBS_JOBID}.txt
		done
	done
done

torque-launch -p "$logdir/chk_L1stats_${sub}_${PBS_JOBID}.txt" "$logdir/cmd_L1stats_${sub}_${PBS_JOBID}.txt"
